### ISSUE TITLE
[FEATURE]: Docker-compose

### ISSUE THREAD

**Issue by nas-maker** [kubero-dev/kubero#349] opened 2024-05-23 14:47 UTC
### Description

Add the possibility for users to deploy their app using Docker Compose.

### Possible solution

.

**Comment by mms-gianni** [comment] 2024-05-27 14:45
Nice Idea. But the problem is, that docker-compose is mostly too complex (multiple files) and has different concepts, which makes it difficult for an automated translation to Kubero CRD's. 

Here is an example of complexity: docker-compose does not differentiate between statefulsets and deployments. Additional services don't need to be marked as add-ons. 

This would lead to false expectations and disappointment. So, I need to close this Feature request.

**Closed by mms-gianni** 2024-05-27 14:45 UTC
Labels: Idea/discussion
